# Docker file for github actions CI build
FROM stablecog/ubuntu:22.04

COPY ./server/server /app/server
COPY ./cron/cron /app/cron
COPY ./uploadapi/uploadapi /app/uploadapi
COPY ./language/linguaapi /app/linguaapi

EXPOSE 13337

CMD ["/app/server"]