FROM ubuntu:22.04

RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ca-certificates && \
  rm -rf /var/lib/apt/lists/*

COPY ./server/server /app/server

EXPOSE 13337

CMD ["/app/server"]