kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-cron-deployment
  namespace: qa-stablecog
  labels:
    app: sc-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-cron
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sc-cron
    spec:
      containers:
        - name: sc-cron
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 512Mi
          command: ["/bin/sh", "-c"]
          args: ["/app/cron -all"]
          imagePullPolicy: "Always"
          env:
            - name: GOTRUE_URL
              value: supabase-supabase-auth.qa-supabase:9999
            - name: PUBLIC_API_URL
              value: https://qa-api.stablecog.com
            - name: BUCKET_BASE_URL
              value: https://b.stablecog.com
            - name: PUBLIC_API_URL
              value: https://qa-api.stablecog.com
            - name: DISCORD_WEBHOOK_URL_DEPLOY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: DISCORD_WEBHOOK_URL_DEPLOY
            - name: MEILI_URL
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MEILI_URL
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MEILI_MASTER_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_DB
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: STRIPE_ENDPOINT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: STRIPE_SECRET_KEY
            - name: SUPABASE_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: SUPABASE_ADMIN_KEY
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: REDIS_CONNECTION_STRING
            - name: SC_WORKER_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: SC_WORKER_WEBHOOK_SECRET
            - name: S3_IMG2IMG_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_ACCESS_KEY
            - name: S3_IMG2IMG_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_BUCKET_NAME
            - name: S3_IMG2IMG_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_ENDPOINT
            - name: S3_IMG2IMG_REGION
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_REGION
            - name: S3_IMG2IMG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_SECRET_KEY
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_BUCKET_NAME
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_ENDPOINT
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_REGION
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_SECRET_KEY
            - name: QDRANT_URLS
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_URLS
            - name: QDRANT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_USERNAME
            - name: QDRANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_PASSWORD
            - name: QDRANT_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_COLLECTION_NAME
