kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-server-deployment
  namespace: qa-stablecog
  labels:
    app: sc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-server
  template:
    metadata:
      labels:
        app: sc-server
    spec:
      containers:
        - name: sc-server
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 13337
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 13337
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 13337
            initialDelaySeconds: 15
            periodSeconds: 10
          imagePullPolicy: "Always"
          env:
            - name: GOTRUE_URL
              value: http://supabase-supabase-auth.qa-supabase:9999
            - name: BUCKET_BASE_URL
              value: https://b.stablecog.com
            - name: PUBLIC_API_URL
              value: https://qa-api.stablecog.com
            - name: STRIPE_STARTER_PRODUCT_ID
              value: prod_NPuwbni7ZNkHDO
            - name: STRIPE_PRO_PRODUCT_ID
              value: prod_NPuqoCPVl1u3Qc
            - name: STRIPE_ULTIMATE_PRODUCT_ID
              value: prod_NPuyRRiAU6TPl3
            - name: STRIPE_STARTER_PRICE_ID
              value: price_1Mf56NATa0ehBYTAHkCUablG
            - name: STRIPE_PRO_PRICE_ID
              value: price_1Mf50bATa0ehBYTAPOcfnOjG
            - name: STRIPE_ULTIMATE_PRICE_ID
              value: price_1Mf591ATa0ehBYTA6ggpEEkA
            - name: STRIPE_MEDIUM_PACK_PRICE_ID
              value: price_1MfRaaATa0ehBYTAVRW3LPdR
            - name: STRIPE_MEDIUM_PACK_PRODUCT_ID
              value: prod_NQIAwnD61CSElQ
            - name: STRIPE_LARGE_PACK_PRICE_ID
              value: price_1MhHtWATa0ehBYTAeBRQMXIP
            - name: STRIPE_LARGE_PACK_PRODUCT_ID
              value: prod_NSCIDEdB7ZHb5x
            - name: STRIPE_MEGA_PACK_PRICE_ID
              value: price_1Mr4aEATa0ehBYTAalXOVpeg
            - name: STRIPE_MEGA_PACK_PRODUCT_ID
              value: prod_NcJCespFpjjQJj
            - name: DISCORD_WEBHOOK_URL_DEPLOY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: DISCORD_WEBHOOK_URL_DEPLOY
            - name: MEILI_URL
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MEILI_URL
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MEILI_MASTER_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_DB
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: STRIPE_ENDPOINT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: STRIPE_SECRET_KEY
            - name: SUPABASE_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: SUPABASE_ADMIN_KEY
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: REDIS_CONNECTION_STRING
            - name: SC_WORKER_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: SC_WORKER_WEBHOOK_SECRET
            - name: S3_IMG2IMG_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_ACCESS_KEY
            - name: S3_IMG2IMG_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_BUCKET_NAME
            - name: S3_IMG2IMG_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_ENDPOINT
            - name: S3_IMG2IMG_REGION
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_REGION
            - name: S3_IMG2IMG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_SECRET_KEY
            - name: QDRANT_URLS
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_URLS
            - name: QDRANT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_USERNAME
            - name: QDRANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_PASSWORD
            - name: QDRANT_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_COLLECTION_NAME
            - name: CLIPAPI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIPAPI_ENDPOINT
            - name: CLIPAPI_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIPAPI_SECRET
            - name: CLIPAPI_URLS
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIPAPI_URLS
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_BUCKET_NAME
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_ENDPOINT
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_REGION
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_SECRET_KEY
