// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/stablecog/go-apps/database/ent/deviceinfo"
	"github.com/stablecog/go-apps/database/ent/generation"
	"github.com/stablecog/go-apps/database/ent/predicate"
	"github.com/stablecog/go-apps/database/ent/upscale"
)

// DeviceInfoUpdate is the builder for updating DeviceInfo entities.
type DeviceInfoUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceInfoMutation
}

// Where appends a list predicates to the DeviceInfoUpdate builder.
func (diu *DeviceInfoUpdate) Where(ps ...predicate.DeviceInfo) *DeviceInfoUpdate {
	diu.mutation.Where(ps...)
	return diu
}

// SetType sets the "type" field.
func (diu *DeviceInfoUpdate) SetType(s string) *DeviceInfoUpdate {
	diu.mutation.SetType(s)
	return diu
}

// SetOs sets the "os" field.
func (diu *DeviceInfoUpdate) SetOs(s string) *DeviceInfoUpdate {
	diu.mutation.SetOs(s)
	return diu
}

// SetBrowser sets the "browser" field.
func (diu *DeviceInfoUpdate) SetBrowser(s string) *DeviceInfoUpdate {
	diu.mutation.SetBrowser(s)
	return diu
}

// SetUpdatedAt sets the "updated_at" field.
func (diu *DeviceInfoUpdate) SetUpdatedAt(t time.Time) *DeviceInfoUpdate {
	diu.mutation.SetUpdatedAt(t)
	return diu
}

// AddGenerationIDs adds the "generations" edge to the Generation entity by IDs.
func (diu *DeviceInfoUpdate) AddGenerationIDs(ids ...uuid.UUID) *DeviceInfoUpdate {
	diu.mutation.AddGenerationIDs(ids...)
	return diu
}

// AddGenerations adds the "generations" edges to the Generation entity.
func (diu *DeviceInfoUpdate) AddGenerations(g ...*Generation) *DeviceInfoUpdate {
	ids := make([]uuid.UUID, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return diu.AddGenerationIDs(ids...)
}

// AddUpscaleIDs adds the "upscales" edge to the Upscale entity by IDs.
func (diu *DeviceInfoUpdate) AddUpscaleIDs(ids ...uuid.UUID) *DeviceInfoUpdate {
	diu.mutation.AddUpscaleIDs(ids...)
	return diu
}

// AddUpscales adds the "upscales" edges to the Upscale entity.
func (diu *DeviceInfoUpdate) AddUpscales(u ...*Upscale) *DeviceInfoUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return diu.AddUpscaleIDs(ids...)
}

// Mutation returns the DeviceInfoMutation object of the builder.
func (diu *DeviceInfoUpdate) Mutation() *DeviceInfoMutation {
	return diu.mutation
}

// ClearGenerations clears all "generations" edges to the Generation entity.
func (diu *DeviceInfoUpdate) ClearGenerations() *DeviceInfoUpdate {
	diu.mutation.ClearGenerations()
	return diu
}

// RemoveGenerationIDs removes the "generations" edge to Generation entities by IDs.
func (diu *DeviceInfoUpdate) RemoveGenerationIDs(ids ...uuid.UUID) *DeviceInfoUpdate {
	diu.mutation.RemoveGenerationIDs(ids...)
	return diu
}

// RemoveGenerations removes "generations" edges to Generation entities.
func (diu *DeviceInfoUpdate) RemoveGenerations(g ...*Generation) *DeviceInfoUpdate {
	ids := make([]uuid.UUID, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return diu.RemoveGenerationIDs(ids...)
}

// ClearUpscales clears all "upscales" edges to the Upscale entity.
func (diu *DeviceInfoUpdate) ClearUpscales() *DeviceInfoUpdate {
	diu.mutation.ClearUpscales()
	return diu
}

// RemoveUpscaleIDs removes the "upscales" edge to Upscale entities by IDs.
func (diu *DeviceInfoUpdate) RemoveUpscaleIDs(ids ...uuid.UUID) *DeviceInfoUpdate {
	diu.mutation.RemoveUpscaleIDs(ids...)
	return diu
}

// RemoveUpscales removes "upscales" edges to Upscale entities.
func (diu *DeviceInfoUpdate) RemoveUpscales(u ...*Upscale) *DeviceInfoUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return diu.RemoveUpscaleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (diu *DeviceInfoUpdate) Save(ctx context.Context) (int, error) {
	diu.defaults()
	return withHooks[int, DeviceInfoMutation](ctx, diu.sqlSave, diu.mutation, diu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (diu *DeviceInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := diu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (diu *DeviceInfoUpdate) Exec(ctx context.Context) error {
	_, err := diu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (diu *DeviceInfoUpdate) ExecX(ctx context.Context) {
	if err := diu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (diu *DeviceInfoUpdate) defaults() {
	if _, ok := diu.mutation.UpdatedAt(); !ok {
		v := deviceinfo.UpdateDefaultUpdatedAt()
		diu.mutation.SetUpdatedAt(v)
	}
}

func (diu *DeviceInfoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   deviceinfo.Table,
			Columns: deviceinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: deviceinfo.FieldID,
			},
		},
	}
	if ps := diu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := diu.mutation.GetType(); ok {
		_spec.SetField(deviceinfo.FieldType, field.TypeString, value)
	}
	if value, ok := diu.mutation.Os(); ok {
		_spec.SetField(deviceinfo.FieldOs, field.TypeString, value)
	}
	if value, ok := diu.mutation.Browser(); ok {
		_spec.SetField(deviceinfo.FieldBrowser, field.TypeString, value)
	}
	if value, ok := diu.mutation.UpdatedAt(); ok {
		_spec.SetField(deviceinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if diu.mutation.GenerationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.GenerationsTable,
			Columns: []string{deviceinfo.GenerationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: generation.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diu.mutation.RemovedGenerationsIDs(); len(nodes) > 0 && !diu.mutation.GenerationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.GenerationsTable,
			Columns: []string{deviceinfo.GenerationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: generation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diu.mutation.GenerationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.GenerationsTable,
			Columns: []string{deviceinfo.GenerationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: generation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if diu.mutation.UpscalesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.UpscalesTable,
			Columns: []string{deviceinfo.UpscalesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: upscale.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diu.mutation.RemovedUpscalesIDs(); len(nodes) > 0 && !diu.mutation.UpscalesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.UpscalesTable,
			Columns: []string{deviceinfo.UpscalesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: upscale.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diu.mutation.UpscalesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.UpscalesTable,
			Columns: []string{deviceinfo.UpscalesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: upscale.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, diu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deviceinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	diu.mutation.done = true
	return n, nil
}

// DeviceInfoUpdateOne is the builder for updating a single DeviceInfo entity.
type DeviceInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceInfoMutation
}

// SetType sets the "type" field.
func (diuo *DeviceInfoUpdateOne) SetType(s string) *DeviceInfoUpdateOne {
	diuo.mutation.SetType(s)
	return diuo
}

// SetOs sets the "os" field.
func (diuo *DeviceInfoUpdateOne) SetOs(s string) *DeviceInfoUpdateOne {
	diuo.mutation.SetOs(s)
	return diuo
}

// SetBrowser sets the "browser" field.
func (diuo *DeviceInfoUpdateOne) SetBrowser(s string) *DeviceInfoUpdateOne {
	diuo.mutation.SetBrowser(s)
	return diuo
}

// SetUpdatedAt sets the "updated_at" field.
func (diuo *DeviceInfoUpdateOne) SetUpdatedAt(t time.Time) *DeviceInfoUpdateOne {
	diuo.mutation.SetUpdatedAt(t)
	return diuo
}

// AddGenerationIDs adds the "generations" edge to the Generation entity by IDs.
func (diuo *DeviceInfoUpdateOne) AddGenerationIDs(ids ...uuid.UUID) *DeviceInfoUpdateOne {
	diuo.mutation.AddGenerationIDs(ids...)
	return diuo
}

// AddGenerations adds the "generations" edges to the Generation entity.
func (diuo *DeviceInfoUpdateOne) AddGenerations(g ...*Generation) *DeviceInfoUpdateOne {
	ids := make([]uuid.UUID, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return diuo.AddGenerationIDs(ids...)
}

// AddUpscaleIDs adds the "upscales" edge to the Upscale entity by IDs.
func (diuo *DeviceInfoUpdateOne) AddUpscaleIDs(ids ...uuid.UUID) *DeviceInfoUpdateOne {
	diuo.mutation.AddUpscaleIDs(ids...)
	return diuo
}

// AddUpscales adds the "upscales" edges to the Upscale entity.
func (diuo *DeviceInfoUpdateOne) AddUpscales(u ...*Upscale) *DeviceInfoUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return diuo.AddUpscaleIDs(ids...)
}

// Mutation returns the DeviceInfoMutation object of the builder.
func (diuo *DeviceInfoUpdateOne) Mutation() *DeviceInfoMutation {
	return diuo.mutation
}

// ClearGenerations clears all "generations" edges to the Generation entity.
func (diuo *DeviceInfoUpdateOne) ClearGenerations() *DeviceInfoUpdateOne {
	diuo.mutation.ClearGenerations()
	return diuo
}

// RemoveGenerationIDs removes the "generations" edge to Generation entities by IDs.
func (diuo *DeviceInfoUpdateOne) RemoveGenerationIDs(ids ...uuid.UUID) *DeviceInfoUpdateOne {
	diuo.mutation.RemoveGenerationIDs(ids...)
	return diuo
}

// RemoveGenerations removes "generations" edges to Generation entities.
func (diuo *DeviceInfoUpdateOne) RemoveGenerations(g ...*Generation) *DeviceInfoUpdateOne {
	ids := make([]uuid.UUID, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return diuo.RemoveGenerationIDs(ids...)
}

// ClearUpscales clears all "upscales" edges to the Upscale entity.
func (diuo *DeviceInfoUpdateOne) ClearUpscales() *DeviceInfoUpdateOne {
	diuo.mutation.ClearUpscales()
	return diuo
}

// RemoveUpscaleIDs removes the "upscales" edge to Upscale entities by IDs.
func (diuo *DeviceInfoUpdateOne) RemoveUpscaleIDs(ids ...uuid.UUID) *DeviceInfoUpdateOne {
	diuo.mutation.RemoveUpscaleIDs(ids...)
	return diuo
}

// RemoveUpscales removes "upscales" edges to Upscale entities.
func (diuo *DeviceInfoUpdateOne) RemoveUpscales(u ...*Upscale) *DeviceInfoUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return diuo.RemoveUpscaleIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (diuo *DeviceInfoUpdateOne) Select(field string, fields ...string) *DeviceInfoUpdateOne {
	diuo.fields = append([]string{field}, fields...)
	return diuo
}

// Save executes the query and returns the updated DeviceInfo entity.
func (diuo *DeviceInfoUpdateOne) Save(ctx context.Context) (*DeviceInfo, error) {
	diuo.defaults()
	return withHooks[*DeviceInfo, DeviceInfoMutation](ctx, diuo.sqlSave, diuo.mutation, diuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (diuo *DeviceInfoUpdateOne) SaveX(ctx context.Context) *DeviceInfo {
	node, err := diuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (diuo *DeviceInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := diuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (diuo *DeviceInfoUpdateOne) ExecX(ctx context.Context) {
	if err := diuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (diuo *DeviceInfoUpdateOne) defaults() {
	if _, ok := diuo.mutation.UpdatedAt(); !ok {
		v := deviceinfo.UpdateDefaultUpdatedAt()
		diuo.mutation.SetUpdatedAt(v)
	}
}

func (diuo *DeviceInfoUpdateOne) sqlSave(ctx context.Context) (_node *DeviceInfo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   deviceinfo.Table,
			Columns: deviceinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: deviceinfo.FieldID,
			},
		},
	}
	id, ok := diuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := diuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deviceinfo.FieldID)
		for _, f := range fields {
			if !deviceinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deviceinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := diuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := diuo.mutation.GetType(); ok {
		_spec.SetField(deviceinfo.FieldType, field.TypeString, value)
	}
	if value, ok := diuo.mutation.Os(); ok {
		_spec.SetField(deviceinfo.FieldOs, field.TypeString, value)
	}
	if value, ok := diuo.mutation.Browser(); ok {
		_spec.SetField(deviceinfo.FieldBrowser, field.TypeString, value)
	}
	if value, ok := diuo.mutation.UpdatedAt(); ok {
		_spec.SetField(deviceinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if diuo.mutation.GenerationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.GenerationsTable,
			Columns: []string{deviceinfo.GenerationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: generation.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diuo.mutation.RemovedGenerationsIDs(); len(nodes) > 0 && !diuo.mutation.GenerationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.GenerationsTable,
			Columns: []string{deviceinfo.GenerationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: generation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diuo.mutation.GenerationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.GenerationsTable,
			Columns: []string{deviceinfo.GenerationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: generation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if diuo.mutation.UpscalesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.UpscalesTable,
			Columns: []string{deviceinfo.UpscalesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: upscale.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diuo.mutation.RemovedUpscalesIDs(); len(nodes) > 0 && !diuo.mutation.UpscalesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.UpscalesTable,
			Columns: []string{deviceinfo.UpscalesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: upscale.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := diuo.mutation.UpscalesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinfo.UpscalesTable,
			Columns: []string{deviceinfo.UpscalesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: upscale.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeviceInfo{config: diuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, diuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deviceinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	diuo.mutation.done = true
	return _node, nil
}
