// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/stablecog/sc-go/database/ent/generationoutput"
	"github.com/stablecog/sc-go/database/ent/generationoutputembed"
	"github.com/stablecog/sc-go/database/ent/predicate"
)

// GenerationOutputEmbedQuery is the builder for querying GenerationOutputEmbed entities.
type GenerationOutputEmbedQuery struct {
	config
	ctx                   *QueryContext
	order                 []OrderFunc
	inters                []Interceptor
	predicates            []predicate.GenerationOutputEmbed
	withGenerationOutputs *GenerationOutputQuery
	modifiers             []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GenerationOutputEmbedQuery builder.
func (goeq *GenerationOutputEmbedQuery) Where(ps ...predicate.GenerationOutputEmbed) *GenerationOutputEmbedQuery {
	goeq.predicates = append(goeq.predicates, ps...)
	return goeq
}

// Limit the number of records to be returned by this query.
func (goeq *GenerationOutputEmbedQuery) Limit(limit int) *GenerationOutputEmbedQuery {
	goeq.ctx.Limit = &limit
	return goeq
}

// Offset to start from.
func (goeq *GenerationOutputEmbedQuery) Offset(offset int) *GenerationOutputEmbedQuery {
	goeq.ctx.Offset = &offset
	return goeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (goeq *GenerationOutputEmbedQuery) Unique(unique bool) *GenerationOutputEmbedQuery {
	goeq.ctx.Unique = &unique
	return goeq
}

// Order specifies how the records should be ordered.
func (goeq *GenerationOutputEmbedQuery) Order(o ...OrderFunc) *GenerationOutputEmbedQuery {
	goeq.order = append(goeq.order, o...)
	return goeq
}

// QueryGenerationOutputs chains the current query on the "generation_outputs" edge.
func (goeq *GenerationOutputEmbedQuery) QueryGenerationOutputs() *GenerationOutputQuery {
	query := (&GenerationOutputClient{config: goeq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := goeq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := goeq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(generationoutputembed.Table, generationoutputembed.FieldID, selector),
			sqlgraph.To(generationoutput.Table, generationoutput.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, generationoutputembed.GenerationOutputsTable, generationoutputembed.GenerationOutputsColumn),
		)
		fromU = sqlgraph.SetNeighbors(goeq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GenerationOutputEmbed entity from the query.
// Returns a *NotFoundError when no GenerationOutputEmbed was found.
func (goeq *GenerationOutputEmbedQuery) First(ctx context.Context) (*GenerationOutputEmbed, error) {
	nodes, err := goeq.Limit(1).All(setContextOp(ctx, goeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{generationoutputembed.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) FirstX(ctx context.Context) *GenerationOutputEmbed {
	node, err := goeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GenerationOutputEmbed ID from the query.
// Returns a *NotFoundError when no GenerationOutputEmbed ID was found.
func (goeq *GenerationOutputEmbedQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = goeq.Limit(1).IDs(setContextOp(ctx, goeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{generationoutputembed.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := goeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GenerationOutputEmbed entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GenerationOutputEmbed entity is found.
// Returns a *NotFoundError when no GenerationOutputEmbed entities are found.
func (goeq *GenerationOutputEmbedQuery) Only(ctx context.Context) (*GenerationOutputEmbed, error) {
	nodes, err := goeq.Limit(2).All(setContextOp(ctx, goeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{generationoutputembed.Label}
	default:
		return nil, &NotSingularError{generationoutputembed.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) OnlyX(ctx context.Context) *GenerationOutputEmbed {
	node, err := goeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GenerationOutputEmbed ID in the query.
// Returns a *NotSingularError when more than one GenerationOutputEmbed ID is found.
// Returns a *NotFoundError when no entities are found.
func (goeq *GenerationOutputEmbedQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = goeq.Limit(2).IDs(setContextOp(ctx, goeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{generationoutputembed.Label}
	default:
		err = &NotSingularError{generationoutputembed.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := goeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GenerationOutputEmbeds.
func (goeq *GenerationOutputEmbedQuery) All(ctx context.Context) ([]*GenerationOutputEmbed, error) {
	ctx = setContextOp(ctx, goeq.ctx, "All")
	if err := goeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GenerationOutputEmbed, *GenerationOutputEmbedQuery]()
	return withInterceptors[[]*GenerationOutputEmbed](ctx, goeq, qr, goeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) AllX(ctx context.Context) []*GenerationOutputEmbed {
	nodes, err := goeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GenerationOutputEmbed IDs.
func (goeq *GenerationOutputEmbedQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	ctx = setContextOp(ctx, goeq.ctx, "IDs")
	if err := goeq.Select(generationoutputembed.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := goeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (goeq *GenerationOutputEmbedQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, goeq.ctx, "Count")
	if err := goeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, goeq, querierCount[*GenerationOutputEmbedQuery](), goeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) CountX(ctx context.Context) int {
	count, err := goeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (goeq *GenerationOutputEmbedQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, goeq.ctx, "Exist")
	switch _, err := goeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (goeq *GenerationOutputEmbedQuery) ExistX(ctx context.Context) bool {
	exist, err := goeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GenerationOutputEmbedQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (goeq *GenerationOutputEmbedQuery) Clone() *GenerationOutputEmbedQuery {
	if goeq == nil {
		return nil
	}
	return &GenerationOutputEmbedQuery{
		config:                goeq.config,
		ctx:                   goeq.ctx.Clone(),
		order:                 append([]OrderFunc{}, goeq.order...),
		inters:                append([]Interceptor{}, goeq.inters...),
		predicates:            append([]predicate.GenerationOutputEmbed{}, goeq.predicates...),
		withGenerationOutputs: goeq.withGenerationOutputs.Clone(),
		// clone intermediate query.
		sql:  goeq.sql.Clone(),
		path: goeq.path,
	}
}

// WithGenerationOutputs tells the query-builder to eager-load the nodes that are connected to
// the "generation_outputs" edge. The optional arguments are used to configure the query builder of the edge.
func (goeq *GenerationOutputEmbedQuery) WithGenerationOutputs(opts ...func(*GenerationOutputQuery)) *GenerationOutputEmbedQuery {
	query := (&GenerationOutputClient{config: goeq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	goeq.withGenerationOutputs = query
	return goeq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PromptEmbedding pgvector.Vector `json:"prompt_embedding,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GenerationOutputEmbed.Query().
//		GroupBy(generationoutputembed.FieldPromptEmbedding).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (goeq *GenerationOutputEmbedQuery) GroupBy(field string, fields ...string) *GenerationOutputEmbedGroupBy {
	goeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GenerationOutputEmbedGroupBy{build: goeq}
	grbuild.flds = &goeq.ctx.Fields
	grbuild.label = generationoutputembed.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PromptEmbedding pgvector.Vector `json:"prompt_embedding,omitempty"`
//	}
//
//	client.GenerationOutputEmbed.Query().
//		Select(generationoutputembed.FieldPromptEmbedding).
//		Scan(ctx, &v)
func (goeq *GenerationOutputEmbedQuery) Select(fields ...string) *GenerationOutputEmbedSelect {
	goeq.ctx.Fields = append(goeq.ctx.Fields, fields...)
	sbuild := &GenerationOutputEmbedSelect{GenerationOutputEmbedQuery: goeq}
	sbuild.label = generationoutputembed.Label
	sbuild.flds, sbuild.scan = &goeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GenerationOutputEmbedSelect configured with the given aggregations.
func (goeq *GenerationOutputEmbedQuery) Aggregate(fns ...AggregateFunc) *GenerationOutputEmbedSelect {
	return goeq.Select().Aggregate(fns...)
}

func (goeq *GenerationOutputEmbedQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range goeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, goeq); err != nil {
				return err
			}
		}
	}
	for _, f := range goeq.ctx.Fields {
		if !generationoutputembed.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if goeq.path != nil {
		prev, err := goeq.path(ctx)
		if err != nil {
			return err
		}
		goeq.sql = prev
	}
	return nil
}

func (goeq *GenerationOutputEmbedQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GenerationOutputEmbed, error) {
	var (
		nodes       = []*GenerationOutputEmbed{}
		_spec       = goeq.querySpec()
		loadedTypes = [1]bool{
			goeq.withGenerationOutputs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GenerationOutputEmbed).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GenerationOutputEmbed{config: goeq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(goeq.modifiers) > 0 {
		_spec.Modifiers = goeq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, goeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := goeq.withGenerationOutputs; query != nil {
		if err := goeq.loadGenerationOutputs(ctx, query, nodes, nil,
			func(n *GenerationOutputEmbed, e *GenerationOutput) { n.Edges.GenerationOutputs = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (goeq *GenerationOutputEmbedQuery) loadGenerationOutputs(ctx context.Context, query *GenerationOutputQuery, nodes []*GenerationOutputEmbed, init func(*GenerationOutputEmbed), assign func(*GenerationOutputEmbed, *GenerationOutput)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GenerationOutputEmbed)
	for i := range nodes {
		fk := nodes[i].OutputID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(generationoutput.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "output_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (goeq *GenerationOutputEmbedQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := goeq.querySpec()
	if len(goeq.modifiers) > 0 {
		_spec.Modifiers = goeq.modifiers
	}
	_spec.Node.Columns = goeq.ctx.Fields
	if len(goeq.ctx.Fields) > 0 {
		_spec.Unique = goeq.ctx.Unique != nil && *goeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, goeq.driver, _spec)
}

func (goeq *GenerationOutputEmbedQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   generationoutputembed.Table,
			Columns: generationoutputembed.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: generationoutputembed.FieldID,
			},
		},
		From:   goeq.sql,
		Unique: true,
	}
	if unique := goeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := goeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, generationoutputembed.FieldID)
		for i := range fields {
			if fields[i] != generationoutputembed.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := goeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := goeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := goeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := goeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (goeq *GenerationOutputEmbedQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(goeq.driver.Dialect())
	t1 := builder.Table(generationoutputembed.Table)
	columns := goeq.ctx.Fields
	if len(columns) == 0 {
		columns = generationoutputembed.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if goeq.sql != nil {
		selector = goeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if goeq.ctx.Unique != nil && *goeq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range goeq.modifiers {
		m(selector)
	}
	for _, p := range goeq.predicates {
		p(selector)
	}
	for _, p := range goeq.order {
		p(selector)
	}
	if offset := goeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := goeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (goeq *GenerationOutputEmbedQuery) Modify(modifiers ...func(s *sql.Selector)) *GenerationOutputEmbedSelect {
	goeq.modifiers = append(goeq.modifiers, modifiers...)
	return goeq.Select()
}

// GenerationOutputEmbedGroupBy is the group-by builder for GenerationOutputEmbed entities.
type GenerationOutputEmbedGroupBy struct {
	selector
	build *GenerationOutputEmbedQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (goegb *GenerationOutputEmbedGroupBy) Aggregate(fns ...AggregateFunc) *GenerationOutputEmbedGroupBy {
	goegb.fns = append(goegb.fns, fns...)
	return goegb
}

// Scan applies the selector query and scans the result into the given value.
func (goegb *GenerationOutputEmbedGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, goegb.build.ctx, "GroupBy")
	if err := goegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GenerationOutputEmbedQuery, *GenerationOutputEmbedGroupBy](ctx, goegb.build, goegb, goegb.build.inters, v)
}

func (goegb *GenerationOutputEmbedGroupBy) sqlScan(ctx context.Context, root *GenerationOutputEmbedQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(goegb.fns))
	for _, fn := range goegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*goegb.flds)+len(goegb.fns))
		for _, f := range *goegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*goegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := goegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GenerationOutputEmbedSelect is the builder for selecting fields of GenerationOutputEmbed entities.
type GenerationOutputEmbedSelect struct {
	*GenerationOutputEmbedQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (goes *GenerationOutputEmbedSelect) Aggregate(fns ...AggregateFunc) *GenerationOutputEmbedSelect {
	goes.fns = append(goes.fns, fns...)
	return goes
}

// Scan applies the selector query and scans the result into the given value.
func (goes *GenerationOutputEmbedSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, goes.ctx, "Select")
	if err := goes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GenerationOutputEmbedQuery, *GenerationOutputEmbedSelect](ctx, goes.GenerationOutputEmbedQuery, goes, goes.inters, v)
}

func (goes *GenerationOutputEmbedSelect) sqlScan(ctx context.Context, root *GenerationOutputEmbedQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(goes.fns))
	for _, fn := range goes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*goes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := goes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (goes *GenerationOutputEmbedSelect) Modify(modifiers ...func(s *sql.Selector)) *GenerationOutputEmbedSelect {
	goes.modifiers = append(goes.modifiers, modifiers...)
	return goes
}
