// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/stablecog/sc-go/database/ent/predicate"
	"github.com/stablecog/sc-go/database/ent/voiceover"
	"github.com/stablecog/sc-go/database/ent/voiceoveroutput"
)

// VoiceoverOutputQuery is the builder for querying VoiceoverOutput entities.
type VoiceoverOutputQuery struct {
	config
	ctx            *QueryContext
	order          []OrderFunc
	inters         []Interceptor
	predicates     []predicate.VoiceoverOutput
	withVoiceovers *VoiceoverQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoiceoverOutputQuery builder.
func (voq *VoiceoverOutputQuery) Where(ps ...predicate.VoiceoverOutput) *VoiceoverOutputQuery {
	voq.predicates = append(voq.predicates, ps...)
	return voq
}

// Limit the number of records to be returned by this query.
func (voq *VoiceoverOutputQuery) Limit(limit int) *VoiceoverOutputQuery {
	voq.ctx.Limit = &limit
	return voq
}

// Offset to start from.
func (voq *VoiceoverOutputQuery) Offset(offset int) *VoiceoverOutputQuery {
	voq.ctx.Offset = &offset
	return voq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (voq *VoiceoverOutputQuery) Unique(unique bool) *VoiceoverOutputQuery {
	voq.ctx.Unique = &unique
	return voq
}

// Order specifies how the records should be ordered.
func (voq *VoiceoverOutputQuery) Order(o ...OrderFunc) *VoiceoverOutputQuery {
	voq.order = append(voq.order, o...)
	return voq
}

// QueryVoiceovers chains the current query on the "voiceovers" edge.
func (voq *VoiceoverOutputQuery) QueryVoiceovers() *VoiceoverQuery {
	query := (&VoiceoverClient{config: voq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := voq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := voq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(voiceoveroutput.Table, voiceoveroutput.FieldID, selector),
			sqlgraph.To(voiceover.Table, voiceover.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voiceoveroutput.VoiceoversTable, voiceoveroutput.VoiceoversColumn),
		)
		fromU = sqlgraph.SetNeighbors(voq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VoiceoverOutput entity from the query.
// Returns a *NotFoundError when no VoiceoverOutput was found.
func (voq *VoiceoverOutputQuery) First(ctx context.Context) (*VoiceoverOutput, error) {
	nodes, err := voq.Limit(1).All(setContextOp(ctx, voq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{voiceoveroutput.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) FirstX(ctx context.Context) *VoiceoverOutput {
	node, err := voq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoiceoverOutput ID from the query.
// Returns a *NotFoundError when no VoiceoverOutput ID was found.
func (voq *VoiceoverOutputQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = voq.Limit(1).IDs(setContextOp(ctx, voq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{voiceoveroutput.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := voq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoiceoverOutput entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoiceoverOutput entity is found.
// Returns a *NotFoundError when no VoiceoverOutput entities are found.
func (voq *VoiceoverOutputQuery) Only(ctx context.Context) (*VoiceoverOutput, error) {
	nodes, err := voq.Limit(2).All(setContextOp(ctx, voq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{voiceoveroutput.Label}
	default:
		return nil, &NotSingularError{voiceoveroutput.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) OnlyX(ctx context.Context) *VoiceoverOutput {
	node, err := voq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoiceoverOutput ID in the query.
// Returns a *NotSingularError when more than one VoiceoverOutput ID is found.
// Returns a *NotFoundError when no entities are found.
func (voq *VoiceoverOutputQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = voq.Limit(2).IDs(setContextOp(ctx, voq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{voiceoveroutput.Label}
	default:
		err = &NotSingularError{voiceoveroutput.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := voq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoiceoverOutputs.
func (voq *VoiceoverOutputQuery) All(ctx context.Context) ([]*VoiceoverOutput, error) {
	ctx = setContextOp(ctx, voq.ctx, "All")
	if err := voq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VoiceoverOutput, *VoiceoverOutputQuery]()
	return withInterceptors[[]*VoiceoverOutput](ctx, voq, qr, voq.inters)
}

// AllX is like All, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) AllX(ctx context.Context) []*VoiceoverOutput {
	nodes, err := voq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoiceoverOutput IDs.
func (voq *VoiceoverOutputQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	ctx = setContextOp(ctx, voq.ctx, "IDs")
	if err := voq.Select(voiceoveroutput.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := voq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (voq *VoiceoverOutputQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, voq.ctx, "Count")
	if err := voq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, voq, querierCount[*VoiceoverOutputQuery](), voq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) CountX(ctx context.Context) int {
	count, err := voq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (voq *VoiceoverOutputQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, voq.ctx, "Exist")
	switch _, err := voq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (voq *VoiceoverOutputQuery) ExistX(ctx context.Context) bool {
	exist, err := voq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoiceoverOutputQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (voq *VoiceoverOutputQuery) Clone() *VoiceoverOutputQuery {
	if voq == nil {
		return nil
	}
	return &VoiceoverOutputQuery{
		config:         voq.config,
		ctx:            voq.ctx.Clone(),
		order:          append([]OrderFunc{}, voq.order...),
		inters:         append([]Interceptor{}, voq.inters...),
		predicates:     append([]predicate.VoiceoverOutput{}, voq.predicates...),
		withVoiceovers: voq.withVoiceovers.Clone(),
		// clone intermediate query.
		sql:  voq.sql.Clone(),
		path: voq.path,
	}
}

// WithVoiceovers tells the query-builder to eager-load the nodes that are connected to
// the "voiceovers" edge. The optional arguments are used to configure the query builder of the edge.
func (voq *VoiceoverOutputQuery) WithVoiceovers(opts ...func(*VoiceoverQuery)) *VoiceoverOutputQuery {
	query := (&VoiceoverClient{config: voq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	voq.withVoiceovers = query
	return voq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AudioPath string `json:"audio_path,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoiceoverOutput.Query().
//		GroupBy(voiceoveroutput.FieldAudioPath).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (voq *VoiceoverOutputQuery) GroupBy(field string, fields ...string) *VoiceoverOutputGroupBy {
	voq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VoiceoverOutputGroupBy{build: voq}
	grbuild.flds = &voq.ctx.Fields
	grbuild.label = voiceoveroutput.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AudioPath string `json:"audio_path,omitempty"`
//	}
//
//	client.VoiceoverOutput.Query().
//		Select(voiceoveroutput.FieldAudioPath).
//		Scan(ctx, &v)
func (voq *VoiceoverOutputQuery) Select(fields ...string) *VoiceoverOutputSelect {
	voq.ctx.Fields = append(voq.ctx.Fields, fields...)
	sbuild := &VoiceoverOutputSelect{VoiceoverOutputQuery: voq}
	sbuild.label = voiceoveroutput.Label
	sbuild.flds, sbuild.scan = &voq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VoiceoverOutputSelect configured with the given aggregations.
func (voq *VoiceoverOutputQuery) Aggregate(fns ...AggregateFunc) *VoiceoverOutputSelect {
	return voq.Select().Aggregate(fns...)
}

func (voq *VoiceoverOutputQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range voq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, voq); err != nil {
				return err
			}
		}
	}
	for _, f := range voq.ctx.Fields {
		if !voiceoveroutput.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if voq.path != nil {
		prev, err := voq.path(ctx)
		if err != nil {
			return err
		}
		voq.sql = prev
	}
	return nil
}

func (voq *VoiceoverOutputQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoiceoverOutput, error) {
	var (
		nodes       = []*VoiceoverOutput{}
		_spec       = voq.querySpec()
		loadedTypes = [1]bool{
			voq.withVoiceovers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoiceoverOutput).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoiceoverOutput{config: voq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(voq.modifiers) > 0 {
		_spec.Modifiers = voq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, voq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := voq.withVoiceovers; query != nil {
		if err := voq.loadVoiceovers(ctx, query, nodes, nil,
			func(n *VoiceoverOutput, e *Voiceover) { n.Edges.Voiceovers = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (voq *VoiceoverOutputQuery) loadVoiceovers(ctx context.Context, query *VoiceoverQuery, nodes []*VoiceoverOutput, init func(*VoiceoverOutput), assign func(*VoiceoverOutput, *Voiceover)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VoiceoverOutput)
	for i := range nodes {
		fk := nodes[i].VoiceoverID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(voiceover.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "voiceover_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (voq *VoiceoverOutputQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := voq.querySpec()
	if len(voq.modifiers) > 0 {
		_spec.Modifiers = voq.modifiers
	}
	_spec.Node.Columns = voq.ctx.Fields
	if len(voq.ctx.Fields) > 0 {
		_spec.Unique = voq.ctx.Unique != nil && *voq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, voq.driver, _spec)
}

func (voq *VoiceoverOutputQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   voiceoveroutput.Table,
			Columns: voiceoveroutput.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: voiceoveroutput.FieldID,
			},
		},
		From:   voq.sql,
		Unique: true,
	}
	if unique := voq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := voq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voiceoveroutput.FieldID)
		for i := range fields {
			if fields[i] != voiceoveroutput.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := voq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := voq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := voq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := voq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (voq *VoiceoverOutputQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(voq.driver.Dialect())
	t1 := builder.Table(voiceoveroutput.Table)
	columns := voq.ctx.Fields
	if len(columns) == 0 {
		columns = voiceoveroutput.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if voq.sql != nil {
		selector = voq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if voq.ctx.Unique != nil && *voq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range voq.modifiers {
		m(selector)
	}
	for _, p := range voq.predicates {
		p(selector)
	}
	for _, p := range voq.order {
		p(selector)
	}
	if offset := voq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := voq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (voq *VoiceoverOutputQuery) Modify(modifiers ...func(s *sql.Selector)) *VoiceoverOutputSelect {
	voq.modifiers = append(voq.modifiers, modifiers...)
	return voq.Select()
}

// VoiceoverOutputGroupBy is the group-by builder for VoiceoverOutput entities.
type VoiceoverOutputGroupBy struct {
	selector
	build *VoiceoverOutputQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vogb *VoiceoverOutputGroupBy) Aggregate(fns ...AggregateFunc) *VoiceoverOutputGroupBy {
	vogb.fns = append(vogb.fns, fns...)
	return vogb
}

// Scan applies the selector query and scans the result into the given value.
func (vogb *VoiceoverOutputGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vogb.build.ctx, "GroupBy")
	if err := vogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoiceoverOutputQuery, *VoiceoverOutputGroupBy](ctx, vogb.build, vogb, vogb.build.inters, v)
}

func (vogb *VoiceoverOutputGroupBy) sqlScan(ctx context.Context, root *VoiceoverOutputQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vogb.fns))
	for _, fn := range vogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vogb.flds)+len(vogb.fns))
		for _, f := range *vogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VoiceoverOutputSelect is the builder for selecting fields of VoiceoverOutput entities.
type VoiceoverOutputSelect struct {
	*VoiceoverOutputQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vos *VoiceoverOutputSelect) Aggregate(fns ...AggregateFunc) *VoiceoverOutputSelect {
	vos.fns = append(vos.fns, fns...)
	return vos
}

// Scan applies the selector query and scans the result into the given value.
func (vos *VoiceoverOutputSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vos.ctx, "Select")
	if err := vos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoiceoverOutputQuery, *VoiceoverOutputSelect](ctx, vos.VoiceoverOutputQuery, vos, vos.inters, v)
}

func (vos *VoiceoverOutputSelect) sqlScan(ctx context.Context, root *VoiceoverOutputQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vos.fns))
	for _, fn := range vos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vos *VoiceoverOutputSelect) Modify(modifiers ...func(s *sql.Selector)) *VoiceoverOutputSelect {
	vos.modifiers = append(vos.modifiers, modifiers...)
	return vos
}
