// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiToken is the predicate function for apitoken builders.
type ApiToken func(*sql.Selector)

// Credit is the predicate function for credit builders.
type Credit func(*sql.Selector)

// CreditType is the predicate function for credittype builders.
type CreditType func(*sql.Selector)

// DeviceInfo is the predicate function for deviceinfo builders.
type DeviceInfo func(*sql.Selector)

// DisposableEmail is the predicate function for disposableemail builders.
type DisposableEmail func(*sql.Selector)

// Generation is the predicate function for generation builders.
type Generation func(*sql.Selector)

// GenerationModel is the predicate function for generationmodel builders.
type GenerationModel func(*sql.Selector)

// GenerationOutput is the predicate function for generationoutput builders.
type GenerationOutput func(*sql.Selector)

// NegativePrompt is the predicate function for negativeprompt builders.
type NegativePrompt func(*sql.Selector)

// Prompt is the predicate function for prompt builders.
type Prompt func(*sql.Selector)

// Scheduler is the predicate function for scheduler builders.
type Scheduler func(*sql.Selector)

// Upscale is the predicate function for upscale builders.
type Upscale func(*sql.Selector)

// UpscaleModel is the predicate function for upscalemodel builders.
type UpscaleModel func(*sql.Selector)

// UpscaleOutput is the predicate function for upscaleoutput builders.
type UpscaleOutput func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
